#!/bin/bash

echo -e '\e[1;31m' 
echo "        ┌───────────────────────────────────┐"
echo "        │   Taking Screenshot. Say Cheese!  │ "
echo "        └───────────────────────────────────┘"
echo "       ╱"
echo "   ▀▄   ▄▀"
echo -e "  ▄█▀███▀█▄ "
echo -e " █▀███████▀█"
echo -e " ▀ ▀▄▄ ▄▄▀ ▀"
echo -e '\e[1;37m'

scrot -cd 2 '%Y-%m-%d--%s_$wx$h_scrot.png' -e 'mv $f ~/images/scrot/ & feh -F ~/images/scrot/$f'
