#!/bin/bash

mycelaneos=$(echo -e "browser\nrange\nrandr\nappearance\ncommander\nmail\nfiles\ngimp\ngba\natari" | dmenu -i -fn "Awesome-14" -nb "#649" -nf "#ff9926" -sb "#f91" -sf "#32f")

case "$mycelaneos" in
        browser) waterfox  ;;
        range) st ranger  ;;
        randr) arandr  ;;
        appearance) lxappearance  ;;
        commander) st mc  ;;
        mail) geary  ;;
        files) pcmanfm  ;;
        gimp) gimp  ;;
        gba) mgba-qt  ;;
        atari) stella  ;;
        *) echo "No option has been selected"  ;;
esac
